import { Box, Typography } from "@mui/material";
import Head from "next/head";
import Form from "../components/Form";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Box sx={{ width: "100%", maxWidth: 600 }}>
          <Typography variant="h3" component="h1" gutterBottom align="center">
            React Hook Form + Material UI components
          </Typography>
          <Form />
        </Box>
      </main>
    </div>
  );
}
